#!/usr/bin/env python3
"""Create Figure 13: Multi-drainage shortfall buffering across LMV mound sites.

Two panels:
  A. Shannon diversity index H (bars) and ordinal observed monument scale
     (dark diamonds, right axis) for the eleven sites in Table 2. Dotted line
     marks the maximum possible Shannon entropy with five equally weighted
     zones (H_max = ln 5 ≈ 1.61).
  B. Number of substantively independent shortfall regimes per site, derived
     from the modern USGS gauge correlation matrix via the script
     `scripts/analysis/water_route_catchment_epsilon.py` (rho >= 0.6
     clustering at access >= 0.5). PP and Lower Jackson sit at the top of the
     LMV interior at 4 regimes each; Jaketown follows at 3; the remaining
     interior sites cluster at 2 (one primary canoe-day drainage plus the
     Macon Ridge upland baseline). The coastal Pearl River pair sits at 2 (estuary + Gulf Flatwoods upland)
     regime (PearlGulf only).

Data sources:
  - Shannon H values from §6.4 Table 2 in `docs/jamt/Manuscript.md`
  - Independent-regime counts from
    `results/sensitivity/water_route_epsilon.json` (regenerated by
    `scripts/analysis/water_route_catchment_epsilon.py` after the
    Cowpen Slough -> OuachitaSystem reassignment of 2026-05-12)
  - Ordinal monument scale from §5 Table 1
"""

import json
from pathlib import Path

import matplotlib.pyplot as plt
import matplotlib as mpl
import numpy as np

PROJECT_ROOT = Path(__file__).resolve().parents[2]
OUTPUT_DIR = PROJECT_ROOT / "figures" / "manuscript"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

WATER_ROUTE_JSON = PROJECT_ROOT / "results" / "sensitivity" / "water_route_epsilon.json"

mpl.rcParams["font.family"] = "sans-serif"
mpl.rcParams["font.size"] = 10
mpl.rcParams["axes.labelsize"] = 10
mpl.rcParams["xtick.labelsize"] = 9
mpl.rcParams["ytick.labelsize"] = 9
mpl.rcParams["legend.fontsize"] = 9

CB = {
    "blue": "#0173B2",
    "orange": "#DE8F05",
    "green": "#029E73",
    "red": "#D55E00",
    "purple": "#CC78BC",
    "brown": "#CA9161",
    "gray": "#888888",
    "yellow": "#ECE133",
    "darkblue": "#093A6B",
}

# Shannon diversity index from §6.4 Table 2 (manuscript line ~411-421).
# Columns of the rubric: aquatic, upland, drainage, mast, prairie.
# H is computed as the Shannon entropy of the zone-weight distribution.
SHANNON_H = {
    "Poverty Point": 1.58,
    "Lower Jackson": 1.55,
    "Watson Brake": 1.38,
    "Caney": 1.38,
    "Frenchman's Bend": 1.38,
    "Insley": 1.37,
    "J.W. Copes": 1.37,
    "Cowpen Slough": 1.36,
    "Jaketown": 1.30,
    # Coastal Pearl River pair: updated Shannon H reflects coastal upland
    # (Gulf Flatwoods) access; Table 2 row weights (1.0, 0.5, 0.5, 0.3, 0.0).
    # Was 0.98 (upland=0.0); now 1.29 (upland=0.5).
    "Claiborne": 1.29,
    "Cedarland": 1.29,
}

# Ordinal monument scale (0 minimal, 1 small, 2 mid, 3 very large).
# Derived from Table 1 prose. Claiborne and Cedarland are treated together
# at scale 1 (shell ring / shell-earth midden).
ORDINAL_SCALE = {
    "Poverty Point": 3,
    "Lower Jackson": 0,
    "Watson Brake": 2,
    "Caney": 2,
    "Frenchman's Bend": 1,
    "Insley": 2,
    "J.W. Copes": 0,
    "Cowpen Slough": 0,
    "Jaketown": 1,
    # Coastal Pearl River pair: both are minimal (single-component
    # construction; Claiborne shell ring, Cedarland shell/earth midden;
    # see Table 1 monument-scale rubric, "minimal = no monument or
    # single-component construction").
    "Claiborne": 0,
    "Cedarland": 0,
}

SCALE_LABELS = {0: "minimal", 1: "small", 2: "mid", 3: "very large"}

# Site display order: PP first, then LMV interior in roughly the Table 1
# sequence, then coastal pair last.
SITE_ORDER = [
    "Poverty Point",
    "Lower Jackson",
    "Watson Brake",
    "Frenchman's Bend",
    "Caney",
    "Insley",
    "J.W. Copes",
    "Cowpen Slough",
    "Jaketown",
    "Claiborne",
    "Cedarland",
]

H_MAX = np.log(5)  # 5 equally weighted zones


def load_independent_regimes():
    """Read independent-regime counts from the water-route catchment JSON."""
    with WATER_ROUTE_JSON.open() as f:
        data = json.load(f)
    return {row["site"]: row["independent_regimes"] for row in data["sites"]}


def main():
    independent_regimes = load_independent_regimes()
    sites = SITE_ORDER
    h_values = [SHANNON_H[s] for s in sites]
    scale_values = [ORDINAL_SCALE[s] for s in sites]
    regime_counts = [independent_regimes[s] for s in sites]
    x = np.arange(len(sites))

    fig, axes = plt.subplots(1, 2, figsize=(13, 5), gridspec_kw={"wspace": 0.30})

    # ---- Panel A: Shannon H bars + ordinal-scale diamonds on right axis
    ax = axes[0]
    bar_colors = [CB["orange"] if s == "Poverty Point" else CB["blue"]
                  for s in sites]
    bars = ax.bar(x, h_values, color=bar_colors, alpha=0.75,
                  edgecolor="black", linewidth=0.6,
                  label="Shannon diversity $H$")
    ax.axhline(H_MAX, color=CB["green"], linestyle=":", linewidth=1.5, alpha=0.7,
               label=f"$H_{{\\max}} = \\ln 5 \\approx {H_MAX:.2f}$")
    ax.set_ylim(0, H_MAX + 0.1)
    ax.set_ylabel("Shannon diversity index $H$ (zone access)")

    # Right axis: ordinal monument scale
    ax2 = ax.twinx()
    ax2.scatter(x, scale_values, color=CB["darkblue"], marker="D",
                s=70, zorder=5, edgecolor="white", linewidth=0.8,
                label="Observed monument scale")
    ax2.set_ylim(-0.4, 3.4)
    ax2.set_yticks([0, 1, 2, 3])
    ax2.set_yticklabels([SCALE_LABELS[i] for i in [0, 1, 2, 3]])
    ax2.set_ylabel("Observed monument scale (ordinal)")

    ax.set_xticks(x)
    ax.set_xticklabels(sites, rotation=40, ha="right")

    # Combined legend
    handles_a, labels_a = ax.get_legend_handles_labels()
    handles_b, labels_b = ax2.get_legend_handles_labels()
    ax.legend(handles_a + handles_b, labels_a + labels_b,
              loc="upper right", framealpha=0.9, fontsize=8)
    ax.text(-0.10, 1.03, "A", transform=ax.transAxes,
            fontsize=14, fontweight="bold")
    ax.set_title("Static-diversity proxy (Shannon $H$) "
                 "vs observed scale", fontsize=10, pad=8)

    # ---- Panel B: Number of independent shortfall regimes per site
    ax = axes[1]
    regime_colors = [CB["orange"] if s == "Poverty Point" else
                     (CB["purple"] if s == "Lower Jackson" else CB["blue"])
                     for s in sites]
    ax.bar(x, regime_counts, color=regime_colors, alpha=0.75,
           edgecolor="black", linewidth=0.6)
    for i, count in enumerate(regime_counts):
        ax.text(i, count + 0.08, str(count),
                ha="center", va="bottom", fontsize=9, fontweight="bold")
    ax.set_ylabel("Independent shortfall regimes (count)")
    ax.set_xticks(x)
    ax.set_xticklabels(sites, rotation=40, ha="right")
    ax.set_ylim(0, max(regime_counts) + 0.8)
    ax.set_yticks(range(0, max(regime_counts) + 1))

    # Annotation explaining the convention
    convention_text = (
        "Strict $\\rho \\geq 0.6$ clustering at access $\\geq 0.5$;\n"
        "Macon Ridge upland counted separately.\n"
        "See Supplemental §S17.4 for per-site outputs."
    )
    ax.text(0.98, 0.97, convention_text, transform=ax.transAxes,
            ha="right", va="top", fontsize=8,
            bbox=dict(boxstyle="round,pad=0.3", facecolor="white",
                      edgecolor=CB["gray"], alpha=0.85))

    ax.text(-0.10, 1.03, "B", transform=ax.transAxes,
            fontsize=14, fontweight="bold")
    ax.set_title("Multi-drainage shortfall buffering "
                 "(independent regimes per site)", fontsize=10, pad=8)

    # Save
    # Output filename matches current Figure 14 numbering (script filename
    # retained as create_figure_13_* for backward compatibility).
    png_path = OUTPUT_DIR / "figure_14_multi_drainage.png"
    pdf_path = OUTPUT_DIR / "figure_14_multi_drainage.pdf"
    plt.savefig(png_path, dpi=300, bbox_inches="tight", facecolor="white")
    plt.savefig(pdf_path, bbox_inches="tight", facecolor="white")
    plt.close()
    print(f"Figure 13 saved to {png_path}")
    print(f"Figure 13 saved to {pdf_path}")


if __name__ == "__main__":
    main()
